name: Generate Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Checkout gh-pages branch
        run: git switch -c gh-pages

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Document
        run: yarn docs

      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Generated docs"
          git push -u origin gh-pages

